### PR TITLE
Prefix any function that returns JSX with _render

### PR DESCRIPTION
**Pull request by rtymchyk**
We do this in several places already. I think it cleans up react components in general in terms of readability.

### CODE REVIEW

**Comment by rtymchyk** [comment]
@tildedave Sorry for rushing on the commit on this - re-submitted as a PR. I'd like to hear why you don't agree with this.

**Comment by tildedave** [comment]
@rtymchyk Basically I'd like to avoid us adding too many style rules, especially those that we've invented ourself.  Even the underscore rule is something that I agree with for my own code but I don't really care if someone deviates from at the moment.

Might be good to look over https://www.npmjs.com/package/eslint-plugin-react for some style rules that are more informed by the community?

**Comment by tildedave** [comment]
Essentially I view this guide as "best practices you should 100% do this" and I want to avoid adding things here that are overly "the team decided to do X" where X isn't also something that has some representation in the broader React community

**Comment by rtymchyk** [comment]
I understand your concern with having too many style rules, and correct me if I'm wrong, but I don't think we need to rely on the react community to improve readability and have consistent naming in our components.

Examples:
* When I'm looking at a function named ```prettyDate```, to me it's pretty vague. I shouldn't have to look at what it does to know what it does. 
* When I'm looking at a huge component like ```CampaignCreateLightbox```, I should know, at a glance, exactly what every function does. Life cycle and private functions should stand out, input event handlers should stand out, and so on.

**Comment by tildedave** [comment]
It sounds like maybe the problem is component size rather than a particular naming convention?

**Pull request closed without merging**
